version: '3.8'
services:
  minecraft:
    image: itzg/minecraft-server:latest
    environment:
      # Use PaperMC
      TYPE: PAPER
      VERSION: "1.21.1"  # Use stable version instead of 1.21.5
      EULA: "TRUE"
      
      # Memory settings
      MEMORY: "4G"
      
      # Server settings
      DIFFICULTY: easy
      MAX_PLAYERS: 20
      VIEW_DISTANCE: 10
      SIMULATION_DISTANCE: 10
      
      # Performance optimizations
      USE_AIKAR_FLAGS: "TRUE"
      
      # Automatic plugin installation (optional)
      # PLUGINS: |
      #   https://github.com/Multiverse/Multiverse-Core/releases/download/4.3.12/multiverse-core-4.3.12.jar
      
      # Automatic restarts
      ENABLE_ROLLING_LOGS: "TRUE"
      
    ports:
      - "25565:25565"
    volumes:
      - minecraft-data:/data
      # Mount plugins directory for easier management
      - ./plugins:/data/plugins
      # Mount logs for debugging
      - ./logs:/data/logs
    restart: unless-stopped
    stdin_open: true
    tty: true
    mem_limit: 5G
    memswap_limit: 5G
    
    healthcheck:
      test: ["CMD-SHELL", "mc-health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 300s
      
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  minecraft-data: