services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    environment:
      EULA: "true"
      TYPE: PAPER
      PLUGINS_FILE: /plugins.txt
      MEMORY: 4G
      VERSION: "1.21.5"
    ports:
      - "25565:25565"
    volumes:
      - mc-data:/data
    restart: unless-stopped
volumes:
  mc-data: {}