multiverse:
  enforce_access: false
  prefixchat: true
  teleportintercept: true
  firstspawnworld: world
  messagecooldown: 5000
  debug: 0
  globalDebug: 0
  silentstart: false
  messagecooldown: 5000
  teleportcooldown: 1000
  defaultportalsearch: false
  portalsearchradius: 128
  autopurge: true
  iocache: true